---
title: "Main"
author: "Ng Joe Hoong"
date: "4/9/2021"
output: html_document
---


```{r load-packages, warning=FALSE}
#if (!require("pacman")) install.packages("pacman")
#pacman::p_load(quantmod, PerformanceAnalytics, dplyr, ggplot2, tidyr)
install.packages("randomForest")

```

```{r}
library(quantmod)
library(tidyverse)
library(PerformanceAnalytics)
library(randomForest)
library(lubridate)

```


```{r get-price-data}

tickers <- c('SPY', 'TLT', 'GLD', 'VXX', 'DBC')
sDate <- as.Date("2009-02-02")
eDate <- as.Date("2020-12-31")


#create price download function
get_symbol <- function(ticker) {
  #Sys.sleep(10) # To prevent alpha vantage 5 calls per minute limit
  Ad(getSymbols(ticker, src="av", api.key="6LVGD8WA484YY2YS", output.size="full", auto.assign=FALSE, from = sDate, to = eDate, warning = FALSE, adjusted=TRUE))
  
}

raw_prices <- do.call(cbind,lapply(tickers,get_symbol))
names(raw_prices) <- gsub("\\..+","",names(raw_prices))  #Remove .Adjusted
tail(raw_prices)

raw_prices <- raw_prices["2009-02-02/2020-12-31"]

write.zoo(raw_prices, file="Data\\raw_prices.csv", sep=",")

```

```{r helper_functions}
calc_equal_risk_weights <- function(returns, lookback=90) {
  n_assets <- ncol(returns)
  vols <- na.omit(apply.rolling(returns[,1], width=lookback, FUN='StdDev.annualized'))
  for (i in 2:n_assets) {
    vols <- merge(vols, na.omit(apply.rolling(returns[,i], width=lookback, FUN='StdDev.annualized')))  
  }

  raw_weights <- 1/vols
  raw_weights[is.infinite(raw_weights)] <- 0
  
  weights <- raw_weights / rowSums(raw_weights) # Normalise weights to add to 1
  colnames(weights) <- colnames(returns)
  
  return(weights)
}

# Convert xts to df for plotting
xts_to_tidy_df <- function(x) {
  df <- cbind(zoo::index(x), as.data.frame(coredata(x)))
  colnames(df)[1] <- 'Date'
  gather(df, key='Asset', value='Value', -Date) 
}


# Performance summary function.
# Returns summary details and prints charts and tables as side effects
riskperformance <- function(returns, weights, samplefreq = 'days', plot = TRUE) {
  # ret <- returns_daily[,-5]
  # weights <- adjweights
  dailyweights <- xts(matrix(NA, nrow(returns), ncol(returns)), order.by = zoo::index(returns))
  dailyweights[zoo::index(weights),] <- coredata(weights)
  dailyweights <- na.omit(na.locf(dailyweights))
  
    # Now scale the returns by the asset weights
  scaleret <- xts::lag.xts(dailyweights,1) * returns
  colnames(scaleret) <- colnames(returns)
  
  
  # Performance
  portfolio_returns <- xts(rowSums(scaleret), order.by=zoo::index(scaleret))


  t <- table.AnnualizedReturns(portfolio_returns)
  cagr <- t[,1][1] * 100
  sharpe <- t[,1][3]
  perf <- data.frame(cagr, sharpe)

  if (plot == TRUE) {
    
    # Weights
    print(plot(weights, main='Asset weights', legend.loc='topleft'))
    weights_df <- xts_to_tidy_df(weights)
    print(ggplot(weights_df, aes(x=Date, y=Value, fill=Asset)) + geom_area() + ggtitle('Asset Weights'))
    
    # Performance
    print(table.DownsideRisk(portfolio_returns))
    print(table.Drawdowns(portfolio_returns))
    charts.PerformanceSummary(portfolio_returns, main = 'Portfolio Returns')
    print(perf)
  }
  return(perf)
}



```


```{r Calculate returns}

raw_prices <- as.xts(read.zoo("Data\\raw_prices.csv", read=read.csv))
#raw_prices2$VXZ <- NULL
raw_prices <- na.omit(raw_prices)
returns <- na.omit(Return.calculate(raw_prices, method='discrete')) 
strat_returns <- returns # Create a copy of returns for incorporating strategy returns as an asset class

#Filter for periods where S&P has fallen more than 5% over past 63 days
# momo <- na.omit(xts::lag.xts(TTR::ROC(raw_prices$SPY, n=63, type='discrete'),1))
# momo$flag <- 0
# momo$flag[momo$SPY < -0.05] <- 1
# 
# returns <- merge(returns, momo$flag, join="left", fill=0)
# returns$VIXstrat <- returns$VXX * returns$flag
# returns$VXX <- NULL
# returns$flag <- NULL


raw_weights <- calc_equal_risk_weights(returns)


#IVTS volatility strategy
ivts <- as.xts(read.zoo("Data\\VIX1M.csv", read=read.csv))
ivts <- merge(ivts, as.xts(read.zoo("Data\\VIX3M.csv", read=read.csv)), join="left", fill=na.locf)
colnames(ivts) <- c("VIX1M", "VIX3M")
ivts <- ivts["2009-01-01/"]
ivts$IVTS <- ivts$VIX1M / ivts$VIX3M
ivts$IVTS_lag <- xts::lag.xts(ivts$IVTS,k=1) #prevent lookahead bias
ivts$flag <- 0
ivts$flag[ivts$IVTS_lag > 1.0] <- 1
ivts$flag[ivts$IVTS_lag <= 1.0] <- -1

ivts$flag_longonly <- 0
ivts$flag_longonly[ivts$IVTS_lag > 1.0] <- 1

weights <- merge(raw_weights, ivts$flag, join="left", fill=0)
weights <- merge(weights, ivts$flag_longonly, join="left", fill=0)
weights$IVTSstrat <- weights$VXX * weights$flag
weights$IVTSlongonly_strat <- weights$VXX * weights$flag_longonly
weights$VXX <- NULL
weights$flag <- NULL
weights$flag_longonly <- NULL

strat_returns <- merge(strat_returns, ivts$flag, join="left", fill=0)
strat_returns <- merge(strat_returns, ivts$flag_longonly, join="left", fill=0)
strat_returns$IVTSstrat <- strat_returns$VXX * strat_returns$flag
strat_returns$IVTSlongonly_strat <- strat_returns$VXX * strat_returns$flag_longonly
strat_returns$VXX <- NULL
strat_returns$flag <- NULL
strat_returns$flag_longonly <- NULL


#Commodity strategy - long DBC when its above 50-SMA, and short DBC when its below
raw_prices$DBC_50MA <- na.omit(apply.rolling(raw_prices$DBC, width=50, FUN="mean"))
raw_prices$DBCflag <- 0
raw_prices$DBCflag[raw_prices$DBC < raw_prices$DBC_50MA] <- -1
raw_prices$DBCflag[raw_prices$DBC > raw_prices$DBC_50MA] <- 1
raw_prices$DBCflag_lag <- stats::lag(raw_prices$DBCflag, k=1) #prevent lookahead bias

weights <- merge(weights, raw_prices$DBCflag_lag, join="left", fill=0)
weights$DBCstrat <- weights$DBC * weights$DBCflag_lag
weights$DBC <- NULL
weights$DBCflag_lag <- NULL

strat_returns <- merge(strat_returns, raw_prices$DBCflag_lag, join="left", fill=0)
strat_returns$DBCstrat <- strat_returns$DBC * strat_returns$DBCflag_lag
strat_returns$DBC <- NULL
strat_returns$DBCflag_lag <- NULL

#par(mfrow=c(5,1))
cum_returns <- cumprod(1+strat_returns)
plot(cum_returns$SPY, main="Cumulative returns of SPY")
plot(cum_returns$TLT, main="Cumulative returns of TLT")
plot(cum_returns$GLD, main="Cumulative returns of GLD")
plot(cum_returns$IVTSstrat, main="Cumulative returns of IVTSstrat")
plot(cum_returns$IVTSlongonly_strat, main="Cumulative returns of IVTS long-only strat")
plot(cum_returns$DBCstrat, main="Cumulative returns of DBCstrat")
```


```{r EDA}
#Correlation matrix
res <- cor(cum_returns)
round(res, 2)


```



```{r 60:40 portfolios}
weights_6040 <- returns
weights_6040$SPY <- 0.6
weights_6040$TLT <- 0.4
weights_6040$GLD <- 0.0
weights_6040$VXX <- 0.0
weights_6040$DBC <- 0.0

perf_6040 <- riskperformance(returns, weights_6040)
```




```{r Equal risk portfolio, with full IVTS strategy}
weights_equalrisk <- weights
colnames(weights_equalrisk)[which(names(weights_equalrisk) == "IVTSstrat")] <- "VXX"
colnames(weights_equalrisk)[which(names(weights_equalrisk) == "DBCstrat")] <- "DBC"
weights_equalrisk$IVTSlongonly_strat <- NULL


perf_equalrisk <- riskperformance(returns, weights_equalrisk)


```



```{r Equal risk portfolio, with long-vol IVTS strategy}
weights_equalrisk_longvol <- weights
colnames(weights_equalrisk_longvol)[which(names(weights_equalrisk_longvol) == "IVTSlongonly_strat")] <- "VXX"
colnames(weights_equalrisk_longvol)[which(names(weights_equalrisk_longvol) == "DBCstrat")] <- "DBC"
weights_equalrisk_longvol$IVTSstrat <- NULL


perf_equalrisk <- riskperformance(returns, weights_equalrisk_longvol)


```



Use random forest to classify whether either asset class will return +ve or -ve, based on the various features?

Then group together 

Features
Interest rates and yield curve changes
https://www.quandl.com/data/FED/RIFLGFCY02_N_B-Market-yield-on-U-S-Treasury-securities-at-2-year-constant-maturity-quoted-on-investment-basis-Business-day
https://www.quandl.com/data/FED/RIFLGFCY05_N_B-Market-yield-on-U-S-Treasury-securities-at-5-year-constant-maturity-quoted-on-investment-basis-Business-day
https://www.quandl.com/data/FED/RIFLGFCY10_N_B-Market-yield-on-U-S-Treasury-securities-at-10-year-constant-maturity-quoted-on-investment-basis-Business-day

Fed Fund Futures   https://www.macrotrends.net/2015/fed-funds-rate-historical-chart
Changes in implied volatility term structure
https://fred.stlouisfed.org/series/VIXCLS
https://fred.stlouisfed.org/series/VXVCLS
Momentum factors - 3,6 12 month momentum

value factors - CAPE
https://www.quandl.com/data/MULTPL/SHILLER_PE_RATIO_MONTH-Shiller-PE-Ratio-by-Month



```{r Gather features}




features <- as.xts(read.zoo("Data\\US2year.csv", read=read.csv))
features <- merge(features, as.xts(read.zoo("Data\\US5year.csv", read=read.csv)), join="left", fill=na.locf)
features <- merge(features, as.xts(read.zoo("Data\\US10year.csv", read=read.csv)), join="left", fill=na.locf)
features <- merge(features, as.xts(read.zoo("Data\\fed-funds-rate-historical-chart.csv", read=read.csv)), join="left", fill=na.locf)
features <- merge(features, as.xts(read.zoo("Data\\VIX1M.csv", read=read.csv)), join="left", fill=na.locf)
features <- merge(features, as.xts(read.zoo("Data\\VIX3M.csv", read=read.csv)), join="left", fill=na.locf)
features <- merge(features, as.xts(read.zoo("Data\\MULTPL-SHILLER_PE_RATIO_MONTH.csv", read=read.csv)), join="left", fill=na.locf)

colnames(features) <- c("US2year", "US5year", "US10year", "FedFunds", "VIX1M", "VIX3M", "CAPE" )

features <- features["2009-02-02/"]

features$US2_5 <- features$US5year - features$US2year
features$US5_10 <- features$US10year - features$US5year
features$IVTS <- features$VIX1M / features$VIX3M


momo_adjust <- function(features, col_name, width = 5) {
  temp <- ( features[,col_name] - stats::lag(features[,col_name],width))
  colnames(temp) <- paste(col_name,"_",width,"momo", sep="")
  features <- merge(features,temp)
  return(features)
}

vol_adjust <- function(features, col_name, width = 5) {
  temp <- ( features[,col_name] - stats::lag(features[,col_name],width))/ rollapply(features[,col_name], width=width, FUN = sd)
  colnames(temp) <- paste(col_name,"_",width,"va", sep="")
  features <- merge(features,temp)
  return(features)
}



features <- momo_adjust(features, "US2year", width=5)
features <- momo_adjust(features, "US5year", width=5)
features <- momo_adjust(features, "US10year", width=5)
features <- momo_adjust(features, "FedFunds", width=5)
features <- vol_adjust(features, "VIX1M", width=5)
features <- vol_adjust(features, "VIX3M", width=5)
features <- momo_adjust(features, "US2_5", width=5)
features <- momo_adjust(features, "US5_10", width=5)
features <- vol_adjust(features, "IVTS", width=5)



strat_returns$IVTSlongonly_strat <- NULL

combined <- na.omit(merge(features, strat_returns))

prev_1_returns <- stats::lag(strat_returns, k=1)
prev_2_returns <- stats::lag(strat_returns, k=2)
prev_3_returns <- stats::lag(strat_returns, k=3)
future_returns <- sign(stats::lag(strat_returns, k=-1))

colnames(prev_1_returns) <- paste(colnames(strat_returns),"_prev_1",sep="")
colnames(prev_2_returns) <- paste(colnames(strat_returns),"_prev_2",sep="")
colnames(prev_3_returns) <- paste(colnames(strat_returns),"_prev_3",sep="")
colnames(future_returns) <- paste(colnames(strat_returns),"_future",sep="")

combined <- na.omit(merge(combined, prev_1_returns))
combined <- na.omit(merge(combined, prev_2_returns))
combined <- na.omit(merge(combined, prev_3_returns))
combined <- na.omit(merge(combined, future_returns))

```


```{r run random forest}
run_random_forest <- function(combined_xts, symbol="SPY_future", all_tickers=colnames(future_returns)){
  ticker_to_remove <- all_tickers[all_tickers != symbol]
  combined_data_frame <- as.data.frame(combined[ , -which(names(combined) %in% ticker_to_remove)])
  combined_data_frame[,symbol] <- as.character(combined_data_frame[,symbol])
  combined_data_frame[,symbol] <- as.factor(combined_data_frame[,symbol])
  
  TrainSet <- combined_data_frame[0:(0.7*nrow(combined_data_frame)),]


  
  forest <- randomForest(as.formula(paste(symbol," ~ .", sep="")), data=TrainSet, importance=TRUE)
  return(forest)
}

forest <- run_random_forest(combined, symbol="SPY_future")
```

```{r}
forest <- run_random_forest(combined, symbol="DBCstrat_future")

predValid <- predict(forest, ValidSet, type="class")
mean(predValid == ValidSet$SPY_future)
table(predValid, ValidSet$SPY_future)
#importance(forest)
varImpPlot(forest, n.var=15)

```


```{r Rolling random forest}
train_random_forest <- function(combined_xts, symbol="SPY_future", end_train_date="2015-01-01", all_tickers=colnames(future_returns)){
  ticker_to_remove <- all_tickers[all_tickers != symbol]
  combined_xts <- combined_xts[paste("/",end_train_date,sep="")]
  
  combined_data_frame <- as.data.frame(combined_xts[ , -which(names(combined_xts) %in% ticker_to_remove)])
  combined_data_frame[,symbol] <- as.character(combined_data_frame[,symbol])
  combined_data_frame[,symbol] <- as.factor(combined_data_frame[,symbol])
  
  TrainSet <- combined_data_frame

  
  forest <- randomForest(as.formula(paste(symbol," ~ .", sep="")), data=TrainSet, importance=TRUE)
  return(forest)
}

rolling_random_forest <- function(combined_xts, symbol="SPY", start_valid_date="2015-01-01", end_valid_date="2015-01-31", all_tickers=colnames(future_returns)) {
  ticker_to_remove <- all_tickers[all_tickers != paste(symbol,"_future", sep="")]
  
  #Create column to store output signal from random forests
  temp_combined_xts <- do.call(cbind,setNames(c(list(combined_xts),rep(list(0),length(paste(symbol,"_signal",sep="")))),c("",paste(symbol,"_signal",sep="")))) 
  
  valid_dates_list <- split.xts(index(temp_combined_xts[paste(start_valid_date,"/",end_valid_date, sep="")]), f="months")
  
  for (dates in valid_dates_list){
    #print(dates)
    #print(length(dates))
    
    first_valid_date <- dates[1]
    last_valid_date <- dates[length(dates)]
    #print(first_valid_date)
    #print(last_valid_date)
    
    train_xts <- temp_combined_xts[paste("/",as.Date(first_valid_date)-1,sep="")]
    valid_xts <- temp_combined_xts[paste(as.Date(first_valid_date),"/",as.Date(last_valid_date),sep="")]
    
    forest <- train_random_forest(train_xts, symbol=paste(symbol,"_future", sep=""), end_train_date=as.Date(first_valid_date)-1)
    
    predValid <- predict(forest, valid_xts, type="class")
    #print(predValid)
    
    for (date in dates){
      #print(as.Date(date))
      #print(predValid[date])
      #print(as.numeric(levels(predValid))[predValid[toString(as.Date(date))]]) 
      temp_combined_xts[as.Date(date),paste(symbol,"_signal",sep="")] <- as.numeric(levels(predValid))[predValid[toString(as.Date(date))]]
     }
    
    #print("finished one date list")
    
  }
  
  return(temp_combined_xts)
}


spy_signal <- rolling_random_forest(combined, symbol="SPY", start_valid_date="2015-01-01", end_valid_date="2020-12-31")

forest_signals <- spy_signal$SPY_signal

signal <- rolling_random_forest(combined, symbol="TLT", start_valid_date="2015-01-01", end_valid_date="2020-12-31")

forest_signals <- merge(forest_signals, signal$TLT_signal)

signal <- rolling_random_forest(combined, symbol="GLD", start_valid_date="2015-01-01", end_valid_date="2020-12-31")

forest_signals <- merge(forest_signals, signal$GLD_signal)

signal <- rolling_random_forest(combined, symbol="IVTSstrat", start_valid_date="2015-01-01", end_valid_date="2020-12-31")

forest_signals <- merge(forest_signals, signal$IVTSstrat_signal)

signal <- rolling_random_forest(combined, symbol="DBCstrat", start_valid_date="2015-01-01", end_valid_date="2020-12-31")

forest_signals <- merge(forest_signals, signal$DBCstrat_signal)


```


```{r}
write.zoo(forest_signals, file="Signal\\forest_signals.csv", sep=",")

```


```{r}

forest_signals <- as.xts(read.zoo("Signal\\forest_signals.csv", read=read.csv))
forest_signals <- forest_signals["2015-01-01/2020-12-31"]

forest_weights <- raw_weights["2015-01-01/2020-12-31"]

forest_weights <- forest_weights * (1+0.2*forest_signals)
riskperformance(strat_returns["2015-01-01/2020-12-31"], forest_weights)
```

```{r}
riskperformance(strat_returns["2015-01-01/2020-12-31"], raw_weights["2015-01-01/2020-12-31"])
  
```



#References
https://www.r-bloggers.com/2018/01/how-to-implement-random-forests-in-r/

(better to predict results 10+ days ahead)
https://rstudio-pubs-static.s3.amazonaws.com/412512_27650b0b41af4aa2933e3a8b4e48480e.html  



